# Пропишем версию
version: '3.7'
# Перечислим сервисы
services:
  nginx:
    # Пропишем какой образ мы хотим использовать
    image: nginx:latest
    # Назовем свой контейнер по красивому
    container_name: nginx
    # Проброс портов
    ports:
      - "80:80"
      - "443:443"
    # Проброс папок
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./www:/var/www/
      - ./nginx/logs:/var/log/nginx/
      - ./nginx/html:/usr/share/nginx/html/
    # Укажем зависимости
    links:
      - php

  mysql:

    image: mysql:latest

    restart: always

    ports:
      - "3306:3306"

    container_name: mysql
    # Пропишем настройки, предлагаю использовать вместо mypassword более сложный пароль, он пренадлежит root
    environment:

      - MYSQL_ROOT_PASSWORD=dbpass
      - MYSQL_DATABASE=gb-hldb
      - MYSQL_USER=gb-hluser
      - MYSQL_PASSWORD=gb-hlpass


    volumes:
      - ./mysql:/var/lib/mysql


  php:
    # Билдим с помощью dockerfile указав директорию где он лежит
    build: ./php

    container_name: php-fpm

    volumes:
      - ./www:/var/www

    links:
      - mysql